### ISSUE TITLE
유저 페이지 answers & comments 탭 구현

### ISSUE THREAD

**Issue by yeonkkk** [codestates-seb/seb39_main_049#116]
### Description
유저페이지에서 작성한 답변 및 댓글을 조회할 수 있도록 함

### Todo
- [x] 작성 답변 조회 기능
- [x] 작성 댓글 조회 기능
- [x] 테스트
- [x] API 명세 업데이트

### Due Date
- 09/26

### ETC
프론트엔드 요청 사항 팀 노션 참고
