### ISSUE TITLE
UI 개선점

### ISSUE THREAD

**Issue by Inhoob** [codestates-seb/seb39_main_049#154]
### Description
UI개선점들 모아놓은 곳입니다.

### Due Date
10/05

### Todo
- [x] 검색창 위치 수정
- [x] 유저들 ID와 유저페이지 링킹
- [x] 로그인,회원가입 모달 디자인?
- [x] 페이지 UI 처리
- [x] 작성글 줄바꿈
- [x] 구직데이터
- [x] 카드 UI
- [x] 배너 캐러셀 플레이버튼 위치 조정(상대값으로)
- [x] 로그인 실패시 그 메시지를 표시하고, modal 이 바로 닫히는게 아닌 비밀번호칸으로 돌아간다던가 UI수정
- [x] 질문 post 할 때 post 피드백을 줄 수 있도록
- [x] 로그아웃 할 때 '로그아웃 하시겠습니까?' 물어보는 절차 필요함
- [x] 질문 삭제할 때 리렌더링 발생할 수 있도록
- [x] 메인 페이지 질문 카드 UI(호버기능, box-shaodw)  
- [x] 질문 등록 후 질문 form 리셋 필요함.
- [ ] 좋아요 버튼 클릭시 버튼 모양 바꾸는거 필요
- [x] 메인 페이지 질문카드 사이사이에 마진 때문에 클릭되는것.
- [x] postpage 답변 길어지면 좋아요와 겹치는것.
- [x] 메인페이지 만약 특정 태그의 게시물이 없다면 없다는 걸 표시해주는 컴포넌트 만들기
- [x] 페이지 이동시 최상단 페이지로
- [x] 배너작성
