### ISSUE TITLE
유저에 점수 추가

### ISSUE THREAD

**Issue by klkim1913** [codestates-seb/seb39_main_049#202]
### Description
좋아요 등으로 얻는 점수 항목 추가

### Todo
- [x] badge 객체 추가
- [x] answer,comment 입력시 점수 추가
- [x] 투표받을시 점수 추가
- [x] 테스트
- [x] 테이블 추가
- [ ] 레벨 기준 정하기

### Due Date
- 00/00

### ETC
랭킹 페이지로 이어짐
