### ISSUE TITLE
[FE] Refactoring 요소들

### ISSUE THREAD

**Issue by Inhoob** [codestates-seb/seb39_main_049#242]
### Todo
- [x] 쓸데없는 import, 안 쓰는 변수 삭제
- [x] 네이밍 보이는대로 정리( onClick={()=>handleClick()} ) 이런식으로
- [x] 에러핸들링 전체적으로 수정
