### ISSUE TITLE
Refactoring 

### ISSUE THREAD

**Issue by yeonkkk** [codestates-seb/seb39_main_049#256]
### Description
지난 회의에서 정리한 리팩터링 사항들 정리하여 올립니다.
기한은 임의적으로 이번주까지로 정하니 추가적인 의견있으면 남겨주세요.

### Due Date
10/30

### Todo
- [ ] 컨트롤러 정리: 컨트롤러는 받고 보내는 것만 하도록 함. 컨트롤러에 있던 기존 로직은 서비스로 이동
- [ ] 매퍼 코드도 컨트롤러에서 서비스로 이동
- [ ] 로그인한 유저 정보 중복 코드 처리
- [ ] 제네릭을 최대한 활용하여 안정성 높이기
- [ ] 리턴 값은 빌드타입으로 통일
- [ ] optional 처리로 일괄 작성
- [ ] 전체적으로 예외처리 안된 부분 있는지 확인
- [ ] (선택) 매퍼 대체제가 있다면 코드 변경 (복잡한 매핑 구현 방식 확인하기)
- [ ] answer controller의 test 삭제
- [ ] application.yml 정리

### ETC
놓친부분이 있으면 코멘트 남겨주시면 감사하겠습니다:)

**Comment by yeonkkk** [comment]
+ 채팅 기능까지 구현 후 전체 리팩토링 진행 예정
