### ISSUE TITLE
채팅 기능 구현

### ISSUE THREAD

**Issue by klkim1913** [codestates-seb/seb39_main_049#261]
### Description
웹 소켓으로 채팅 기능 구현, 화상 채팅 기능

### Todo
- [x] 웹 소켓 및 기본 채팅 로직 이해
- [x] 채팅기능 구현
- [ ] 화상채팅 기능(면접 연습용)

### Due Date
- 11/02

### ETC
postman의 웹소켓 테스트를 활용해볼 예정입니다.
필요시 js or thymeleaf 활용.

**Comment by yeonkkk** [comment]
@klkim1913 스터디할 내용이나 각자 구현할 내용 정리하면 좋을 것 같네요.

**Comment by klkim1913** [comment]
> @klkim1913 스터디할 내용이나 각자 구현할 내용 정리하면 좋을 것 같네요.

시간 되실때 얘기 나눠보시져

**Comment by yeonkkk** [comment]
### 10/25 회의 내용 추가

* 구현 상세
  * 단체채팅방
  * 채팅방 목록

* 10/27까지 각자 공부 & 기본 기능 구현 진행

**Comment by yeonkkk** [comment]
### 10/31 백엔드 회의 내용

- back-end
    
    - [ ] websocket  공부
    - [ ] stomp 공부
    - [ ] sockJS 공부
    - [ ] 채팅 코드 수정 

- front-end
    
    - [ ] `room.html` 코드 수정
    - [ ] `roomdetail.html` 코드 수정

**Comment by klkim1913** [comment]
**시간남으면 작업하면 좋을것들**

1. 채팅리스트, 채팅 내용 db 연동
2. 화상채팅 링크 연동

**Comment by klkim1913** [comment]
화상 제외 완
