### ISSUE TITLE
JPA 엔티티 매핑

### ISSUE THREAD

**Issue by yeonkkk** [codestates-seb/seb39_main_049#39]
### Description
User, Question, Answer, Comment 연관관계 매핑 및 ResponseDto 작성

### Todo
- [x] 테이블 연관관계 매핑
- [x] Question ResponseDto 작성
- [x] Comment ResponseDto 작성
- [x] Answer ResponseDto 작성
- [x] postman 테스트

### Due Date
- 09/19

### ETC
ResponseDto 작성 형태 고민
UserResponseDto는 프론트엔드팀에서 멘토님과 상의 후 파라미터 정리해주기로 함
