### ISSUE TITLE
views, votes 기능 구현

### ISSUE THREAD

**Issue by Inhoob** [codestates-seb/seb39_main_049#70]
### Description
views,votes 필요한 부분에 구현

### Todo
- [ ] Question에 views 구현
- [ ] Answer에 votes 구현
- [ ] Comment에 votes 구현(선택)

### Due Date
- 09/22

### ETC
기타 사항 작성해주세요
